version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:11"
      timezone: "Europe/Berlin"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:12"
      timezone: "Europe/Berlin"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:13"
      timezone: "Europe/Berlin"
