name: Build Release

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
      TAG:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true
      SNYK_TOKEN:
        required: true

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
      - name: Test1
        run: echo "Test1"
