name: Docker Builds

on:
  # This workflow can be called from other workflows.
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
        description: The github branch to build from
      TAG:
        required: true
        type: string
        description: The docker tag to build
    secrets:
      SNYK_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
  # This workflow can be triggered manually.
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: string
        description: The github branch to build from
        default: 'main'
      TAG:
        required: true
        type: string
        description: The docker tag to build
        default: 'latest'

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Show versions
        run: |
          echo "BRANCH --> ${{ inputs.BRANCH }}"
          echo "TAG --> ${{ inputs.TAG }}"

      - name: Checkout Code
        uses: actions/checkout@v5.0.0

      - name: Build the Docker Image
        run: docker build --progress=plain --tag franky1/tesseract:${{ inputs.TAG }} --build-arg TESSERACT_VERSION=${{ inputs.BRANCH }} .

      - name: Analyze image efficiency
        uses: yuichielectric/dive-action@0.0.4
        with:
          image: franky1/tesseract:${{ inputs.TAG }}

      - name: Run the Docker Container
        run: docker run --rm franky1/tesseract:${{ inputs.TAG }}

      - name: Test the Docker Container
        run: docker run --rm -v ${PWD}/testdata:/tmp franky1/tesseract:${{ inputs.TAG }} tesseract english.png output --oem 1 -l eng

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@0.4.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: franky1/tesseract:${{ inputs.TAG }}
          args: --file=Dockerfile --sarif-file-output=snyk.sarif

      - name: Login to DockerHub
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push franky1/tesseract:${{ inputs.TAG }}

      - name: Docker Hub Description Update
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: franky1/tesseract
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./Docker-Hub-Description.md
