name: Docker

on:
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
        description: The branch to build from
      TAG:
        required: true
        type: string
        description: The docker tag to build
    secrets:
      SNYK_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
  workflow_dispatch:
    inputs:
      BRANCH:
        required: true
        type: string
        description: The github branch to build from
        default: 'main'
      TAG:
        required: true
        type: string
        description: The docker tag to build
        default: 'latest'
    secrets:
      SNYK_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Show versions
        run: |
          echo "BRANCH --> ${{ inputs.BRANCH }}"
          echo "TAG --> ${{ inputs.TAG }}"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build the Docker Image
        run: docker build --tag franky1/tesseract:${{ inputs.TAG }} --build-arg TESSERACT_VERSION=${{ inputs.BRANCH }} .

      - name: Run the Docker Container
        run: docker run --rm franky1/tesseract:${{ inputs.TAG }}

      - name: Test the Docker Container
        run: docker run --rm -v ${PWD}/testdata:/tmp franky1/tesseract:${{ inputs.TAG }} tesseract english.png output --oem 1 -l eng

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@14818c4695ecc4045f33c9cee9e795a788711ca4
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: franky1/tesseract:${{ inputs.TAG }}
          args: --file=Dockerfile

      - name: Upload Snyk report to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
          category: snyk-docker-${{ inputs.TAG }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push franky1/tesseract:${{ inputs.TAG }}

      - name: Docker Hub Description Update
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: franky1/tesseract
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./Docker-Hub-Description.md
