name: Push Event

on:
  # run on push to main
  push:
    branches:
      - main
  # allow manual trigger from any branch (no branch filters supported here)
  workflow_dispatch:

jobs:
  Linter:
    uses: Franky1/Tesseract-OCR-5-Docker/.github/workflows/linter.yml@main
    with:
      BRANCH: "main"

  Build-Main:
    uses: Franky1/Tesseract-OCR-5-Docker/.github/workflows/docker.yml@main
    with:
      TAG: latest
      BRANCH: main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
