name: Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linter:
    uses: Franky1/Tesseract-OCR-5-Docker/.github/workflows/linter.yml@main
    with:
      BRANCH: "main"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
