name: Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Linter:
    uses: Franky1/Tesseract-OCR-5-Docker/.github/workflows/linter.yml@main
    with:
      BRANCH: "main"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build-Main:
    uses: Franky1/Tesseract-OCR-5-Docker/.github/workflows/docker.yml@main
    with:
      TAG: latest
      BRANCH: main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
