name: Test Python and Scheduler

# env:
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # UPDATE_MAIN: False
  # UPDATE_RELEASE: False

on:
  schedule:
    # Runs "at 04:04 every day" (see https://crontab.guru)
    - cron: '4 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Show Python Version
        run: python --version
      - name: Install PyGithub
        run: pip install --upgrade PyGithub
      - name: Run python script to check for updates
        run: python versioncheck.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: run job for main branch
        if: "test -f UPDATE_MAIN"
        run: echo "UPDATE_MAIN necessary"
        # uses: ./.github/workflows/build-main.yml
      - name: run job for release
        if: "test -f UPDATE_RELEASE"
        run: echo "UPDATE_RELEASE necessary"
        # uses: ./.github/workflows/build-release.yml
