name: Test Python and Scheduler

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # UPDATE_MAIN: False
  # UPDATE_RELEASE: False

on:
  schedule:
    # Runs "at 04:04 every day" (see https://crontab.guru)
    - cron: '4 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Explore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - run: python --version
      - run: pip install --upgrade PyGithub
      - run: python versioncheck.py
      - run: test -f UPDATE_MAIN && echo "$FILE exists."
      - run: test -f UPDATE_RELEASE && echo "$FILE exists."
